# Generated by Django 2.2.1 on 2020-09-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('completion_date', models.DateTimeField()),
            ],
        ),
    ]
