# Generated by Django 2.2.1 on 2020-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0002_auto_20201001_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completion_date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'Planned'), (3, 'In progress'), (4, 'Completed')], max_length=2, verbose_name='Статус'),
        ),
    ]
