# Generated by Django 2.2.1 on 2020-10-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0004_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'Planned'), (3, 'In progress'), (4, 'Completed')], max_length=20, verbose_name='Статус'),
        ),
    ]
