# Generated by Django 2.2.1 on 2020-10-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0006_auto_20201003_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskchangehistory',
            old_name='change_fields',
            new_name='changed_fields',
        ),
    ]
