# Generated by Django 2.2.1 on 2020-10-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0009_taskchangehistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskchangehistory',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=20, verbose_name='Статус'),
        ),
    ]
